version: "3.9"
services:
  app:
    build:
      context: .
    container_name: gmbc
    depends_on:
      - postgres
    env_file:
      - ./app.env
    ports:
      - "8082:8082"
    restart: on-failure
    volumes:
      - "$HOME/.ssh:/root/.ssh"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./app.env
    ports:
      - "54320:5432"
    restart: on-failure
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"