services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8080"
#      - "9090:9090"
#    env_file:
#      - ./app.env
#    environment:
#      - DB_SOURCE=
#    depends_on:
#      - postgres
#    entrypoint:
#      [
#        "/app/wait-for.sh",
#        "postgres:5432",
#        "--",
#        "/app/start.sh"
#      ]
#    command: [ "/app/main" ]
#    volumes:
#      - "${HOME}/.ssh:/root/.ssh"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./app.env
    ports:
      - "54320:5432"
    restart: on-failure
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"