version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./app.env
    ports:
      - "54320:5432"
    restart: always
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"