version: "3.9"
services:
  postgres:
    image: postgres:15-bullseye
    container_name: postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASS="${POSTGRES_PASS}"
      - POSTGRES_DB=simple_bank
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"